FROM python:3.7.9

COPY requirements.txt ./requirements.txt

# this allows to avoid intereactive installations
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && \
	apt install -y software-properties-common apt-utils texlive-base locales \
	texlive-base texlive-latex-extra \
	texlive-fonts-extra texlive-fonts-recommended && \
    pip install -r requirements.txt

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN dpkg-reconfigure --frontend=noninteractive locales && \ 
   export LC_ALL=en_US.UTF-8 && \
   export LC_CTYPE=en_US.UTF-8

# #+++++++++++++++++++++++++++++++++++++++++++++++++++
# FROM ubuntu:20.10
# COPY requirements.txt ./requirements.txt
# ENV DEBIAN_FRONTEND noninteractive

# RUN apt update && \
# 	apt install -y software-properties-common apt-utils locales \
# 	language-pack-en-base python3-pip && \
# 	# texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended && \
#     pip install -r requirements.txt
# #+++++++++++++++++++++++++++++++++++++++++++++++++++
