version: '3'
services:
  server:
      build:
        context: .
      volumes:
        # this means that we map the current content dir to destination dir in container 
        # the mysite parent dire is the workdir set in Dockerfile
        - ./content:/mysite/content
        - ./m.css:/mysite/m.css
      ports:
        - "8080:8080"
